name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # 最小必要（即使 requirements.txt 沒列也能跑）
          pip install pytest pandas numpy fastapi

      - name: Run tests (pytest)
        env:
          # 重要：src-layout
          PYTHONPATH: ${{ github.workspace }}/src
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          # 有特定路徑就跑，沒有就退回跑全部
          if [ -d "tests" ]; then
            pytest -q
          else
            echo "No tests/ directory found"; exit 0
          fi